name: Generate Realistic Neon Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 10

    steps:

      # ==========================================
      # Generate LIGHT neon snake
      # ==========================================

      - name: Generate Light Neon Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: anshumancodehub

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300F5FF&color_dots=%230B1020,%2300BFFF,%23006EFF,%237F00FF,%23FF00C8


      # ==========================================
      # Generate DARK neon snake
      # ==========================================

      - name: Generate Dark Neon Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: anshumancodehub

          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2300F5FF&color_dots=%23050A14,%230066FF,%2300BFFF,%237F00FF,%23FF00C8


      # ==========================================
      # Deploy generated files
      # ==========================================

      - name: Deploy Snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
